name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: freckle/stack-cache-action@main
    - uses: freckle/stack-action@main
      with:
        weeder: false
