name: Nightly Resolver

on:
  pull_request:
  push:
    branches: main

  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: freckle/stack-cache-action@main
    - uses: freckle/stack-action@main
      with:
        stack-arguments: --resolver nightly
        weeder: false
